Capstone-01 Cloud Hosting
MuhmmdUsama/Capstone-Cloud-Hosting pull request #1
Opened 2022-04-18 17:31 UTC by MuhmmdUsama

## build only 2 pages:

- The home page.
- The about page.

## pages have versions for 2 different screen sizes:

- Mobile: up to 768px wide.
- Desktop: 768px or wider.

## Links

- The home page should have a link in the menu to the about page.
- The logo in the header links to the home page.

## Mobile menu

- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page
- The mobile menu has a close (X) button that closes the menu.

## Dynamic page

- The section "Featured speakers" is created dynamically in JavaScript.
- Use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.

2022-04-18 23:07 UTC, OLIPLICHE requested changes
Hi @MuhmmdUsama , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- 👏 👏 👏 👏 👏  I can't stop clapping, your Job is amazing. 
Linter result is green ✔️
 Commit messages are meaningful✔️
 The pull request have a descriptive title telling you what changes are inside ✔️
 The pull request have a short summary describing introduced changes in more detail ✔️
 node_modules folder is in the .gitignore ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-18 23:07 UTC, OLIPLICHE commented on README.md
> +
- [x] Please record a video (use tools like [Loom](https://www.loom.com/)) presenting, the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:
- Description of the project.
- A demo of the project features (different pages and different screen sizes).
- Kindly highlight some interesting pieces of code you built that you are very proud of.

2022-04-18 23:07 UTC, OLIPLICHE commented on index.html
> +        <ul class="list nav__list collapsible__content">
- [x] **Desktop Size**: In your project, It's possible to navigate between the pages, there's a link from `Home` page to `About` page. Please add a link to Navigate from `About` page to `Home` page.

2022-04-18 23:07 UTC, OLIPLICHE commented on index.html
> +        </div>
- [ ] Please add "margin" to push the logo to the left and text aligned to the right. You can use both classes `footer_logo` and `footer_info` to solve it.
- [ ] Kindly build the same footer(white color) to the Home page of your Mobile size. 

![margin](https://user-images.githubusercontent.com/63972670/163884933-024952f4-d7c8-40c1-8510-f5abf58284cd.JPG)

2022-04-18 23:07 UTC, OLIPLICHE commented on index.html
> +        </div>
- [x] Please make sure the middle section includes **five individual articles**, **each with an image, title, and description, and a line of text at the bottom**
- Your Design does not contain individual articles as mentioned above


![five](https://user-images.githubusercontent.com/63972670/163887612-a03efb45-caf7-4a65-b855-0c870b66eb31.JPG)

2022-04-18 23:07 UTC, OLIPLICHE commented on js/main.js
> +    name: 'John smith',
- [ ] Please give the speakers different names. This will make your project looks reel and more attractive. 
![js1](https://user-images.githubusercontent.com/63972670/163889402-465231b3-050b-496d-8eaf-64c1412397b1.JPG)

2022-04-18 23:07 UTC, OLIPLICHE commented on about.html
> +    <section class="partner about__partner">
- [x] **IN MOBILE SIZE** 
Please add **`our Partner section`**  to the `Home page` mobile size. 
- Your Design

![WhatsApp Image 2022-04-18 at 11 51 13 PM](https://user-images.githubusercontent.com/63972670/163890117-b06346e4-9462-49f4-92e8-77e2693ca4d4.jpeg)

2022-04-19 07:38 UTC, MuhmmdUsama commented on README.md
> +
Hi @OLIPLICHE I already recorded the video and placed the link inside the PR description I don't know  where is the problem if I used another app to record the video

2022-04-19 07:46 UTC, MuhmmdUsama commented on index.html
> +        <ul class="list nav__list collapsible__content">
@OLIPLICHE I already did it as they mentioned in the requirement 

- The home page should have a link in the menu to the about page.
- The logo in the header links to the home page.

so I couldn't see again where is the problem

2022-04-19 08:32 UTC, MuhmmdUsama commented on about.html
> +    <section class="partner about__partner">
Hi @OLIPLICHE according to the Behance template there is no partner or footer section in the `Home Page Mobil version `and your screenshot comes from the `About Page`
So I don't understand what's the mistake I did here?!!

2022-04-19 13:15 UTC, MuhmmdUsama commented on index.html
> +        </div>
Ok, it's done

![Screenshot 2022-04-19 151415](https://user-images.githubusercontent.com/45886560/164012323-b8a2f9bf-3cc5-41c2-976e-9aeba418aa84.png)

2022-04-19 13:17 UTC, MuhmmdUsama commented on js/main.js
> +    name: 'John smith',
its done

![Screenshot 2022-04-19 151611](https://user-images.githubusercontent.com/45886560/164012607-07eb84cc-45a8-4164-a5f5-0a4762809a83.png)

2022-04-19 14:19 UTC, micheaol approved these changes
# STATUS: APPROVED :green_circle: :clap: 
Hi @MuhmmdUsama , 

Great work on making the changes 👏 
In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)
Good luck! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-19 14:19 UTC, micheaol commented on js/main.js
> +    name: 'John smith',
Thank you for implementing the changes requested by the previuos code reviewer.
## [OPTIONAL]: 

Please ensure that your mobile version looks exactly like the original design.

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/164024575-d5e50dce-f6b1-4529-a67c-b26cff3c1b3c.png) | ![image](https://user-images.githubusercontent.com/10332499/164024392-746efabd-6bd8-4bd4-afe3-40a803babe04.png)

2022-04-19 14:40 UTC, merged